github:
  username: ${{ secrets.IMPLEMENTATION_GITHUB_USERNAME }}
  token:    ${{ secrets.IMPLEMENTATION_GITHUB_TOKEN }}

codeowners:
- path:  "*"
  owner: "@buildpacks/implementation-maintainers"

test:
  steps:
  - name: Install richgo
    run: |
      #!/usr/bin/env bash

      set -euo pipefail

      echo "Installing richgo ${RICHGO_VERSION}"

      mkdir -p "${HOME}"/bin
      echo "${HOME}/bin" >> "${GITHUB_PATH}"

      curl \
        --location \
        --show-error \
        --silent \
        "https://github.com/kyoh86/richgo/releases/download/v${RICHGO_VERSION}/richgo_${RICHGO_VERSION}_linux_amd64.tar.gz" \
      | tar -C "${HOME}"/bin -xz richgo
    env:
      RICHGO_VERSION: 0.3.10
  - name: Run Tests
    run: |
      #!/usr/bin/env bash

      set -euo pipefail

      GOCMD=richgo make
    env:
      RICHGO_FORCE_COLOR: "1"
