// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// EnvironmentWriter is an autogenerated mock type for the EnvironmentWriter type
type EnvironmentWriter struct {
	mock.Mock
}

// Write provides a mock function with given fields: dir, environment
func (_m *EnvironmentWriter) Write(dir string, environment map[string]string) error {
	ret := _m.Called(dir, environment)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, map[string]string) error); ok {
		r0 = rf(dir, environment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
