// Code generated by mockery v2.24.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// EnvironmentWriter is an autogenerated mock type for the EnvironmentWriter type
type EnvironmentWriter struct {
	mock.Mock
}

// Write provides a mock function with given fields: dir, environment
func (_m *EnvironmentWriter) Write(dir string, environment map[string]string) error {
	ret := _m.Called(dir, environment)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, map[string]string) error); ok {
		r0 = rf(dir, environment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewEnvironmentWriter interface {
	mock.TestingT
	Cleanup(func())
}

// NewEnvironmentWriter creates a new instance of EnvironmentWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEnvironmentWriter(t mockConstructorTestingTNewEnvironmentWriter) *EnvironmentWriter {
	mock := &EnvironmentWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
