// Code generated by mockery 2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ExitHandler is an autogenerated mock type for the ExitHandler type
type ExitHandler struct {
	mock.Mock
}

// Error provides a mock function with given fields: _a0
func (_m *ExitHandler) Error(_a0 error) {
	_m.Called(_a0)
}

// Fail provides a mock function with given fields:
func (_m *ExitHandler) Fail() {
	_m.Called()
}

// Pass provides a mock function with given fields:
func (_m *ExitHandler) Pass() {
	_m.Called()
}
