// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	io "io"

	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// FileWriter is an autogenerated mock type for the FileWriter type
type FileWriter struct {
	mock.Mock
}

// Write provides a mock function with given fields: path, reader
func (_m *FileWriter) Write(path string, reader io.Reader) error {
	ret := _m.Called(path, reader)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, io.Reader) error); ok {
		r0 = rf(path, reader)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewFileWriter creates a new instance of FileWriter. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewFileWriter(t testing.TB) *FileWriter {
	mock := &FileWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
