// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	libcnb "github.com/buildpacks/libcnb"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// SBOMFormatter is an autogenerated mock type for the SBOMFormatter type
type SBOMFormatter struct {
	mock.Mock
}

// Formats provides a mock function with given fields:
func (_m *SBOMFormatter) Formats() []libcnb.SBOMFormat {
	ret := _m.Called()

	var r0 []libcnb.SBOMFormat
	if rf, ok := ret.Get(0).(func() []libcnb.SBOMFormat); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]libcnb.SBOMFormat)
		}
	}

	return r0
}

// NewSBOMFormatter creates a new instance of SBOMFormatter. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewSBOMFormatter(t testing.TB) *SBOMFormatter {
	mock := &SBOMFormatter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
